const fs=require('fs');
const src=fs.readFileSync(__dirname+'/kenti_core.js','utf8');
let CUR=[];
const pcaVarDefs=()=>CUR.map(k=>({k,label:k,sym:k,d:2}));
eval(src+';globalThis.K={alpha,jaccard,morisitaHorn,brayCurtis,upgma,regression,jacobiEigen,tPValue,tCrit,pcaCompute}');
const IN=JSON.parse(fs.readFileSync(__dirname+'/in.json','utf8'));
const out={};
out.alpha=IN.alpha.map(v=>K.alpha(v));
out.beta=IN.beta.map(([a,b])=>({jac:K.jaccard(a,b),mh:K.morisitaHorn(a,b),bc:K.brayCurtis(a,b)}));
out.upgma=IN.upgma.map(({M})=>{const r=K.upgma(M);const n=M.length;const C=M.map(r=>r.map(()=>1));
  (function walk(nd){ if(!nd.left) return; for(const a of nd.left.members) for(const b of nd.right.members){C[a][b]=C[b][a]=nd.h;} walk(nd.left);walk(nd.right);})(r.root);
  return {ccc:r.ccc,C};});
out.pca=IN.pca.map(({X})=>{const p=X[0].length;CUR=[...Array(p).keys()].map(i=>'v'+i);
  const rows=X.map(x=>{const o={};x.forEach((v,i)=>o['v'+i]=v);return o;});
  const r=K.pcaCompute(rows,CUR); if(r.error) return {error:r.error};
  return {p:r.p,n:r.n,lam:r.comps.map(c=>c.lam),load:r.comps.map(c=>c.loadings),scores:r.comps.map(c=>c.scores)};});
out.reg=IN.reg.map(({x,y})=>{const r=K.regression(x,y); return r.ok?{b0:r.b0,b1:r.b1,r:r.r,p:r.p,s:r.s,tc:r.tc,ci0:r.ci(0),mx:r.mx}:{error:r.why};});
out.t=IN.t.map(([t,df])=>({p:K.tPValue(t,df)}));
out.tcrit=IN.tcrit.map(df=>K.tCrit(.05,df));
fs.writeFileSync(__dirname+'/out.json',JSON.stringify(out));
